### ISSUE TITLE
Compilation of Foundation Framework 5.5.2 fails

### ISSUE THREAD

**Issue by dtrunk90** [leafo/scssphp#331]
```
<br />
<b>Fatal error</b>:  Uncaught exception 'Exception' with message 'Undefined variable $include_html_classes: failed at `$include-html-grid-classes: $include-html-classes !default;` line: 10' in /var/www/vendor/leafo/scssphp/src/Parser.php:2142
Stack trace:
#0 /var/www/vendor/leafo/scssphp/src/Compiler.php(2776): Leafo\ScssPhp\Parser-&gt;throwParseError('Undefined varia...', 119)
#1 /var/www/vendor/leafo/scssphp/src/Compiler.php(2516): Leafo\ScssPhp\Compiler-&gt;throwError('Undefined varia...')
#2 /var/www/vendor/leafo/scssphp/src/Compiler.php(1549): Leafo\ScssPhp\Compiler-&gt;get('include-html-cl...')
#3 /var/www/vendor/leafo/scssphp/src/Compiler.php(1084): Leafo\ScssPhp\Compiler-&gt;reduce(Array)
#4 /var/www/vendor/leafo/scssphp/src/Compiler.php(828): Leafo\ScssPhp\Compiler-&gt;compileChild(Array, Object(stdClass))
#5 /var/www/vendor/leafo/scssphp/src/Compiler.php(249): Leafo\ScssPhp\Compiler-&gt;compileChildren(Array, Object(stdClass))
#6 /var/www/vendor/leafo/scssphp/src/Compiler.php(166): Leafo\ScssPhp\Compiler-&gt;compileRoot(Object(stdClass))
#7 in <b>/var/www/vendor/leafo/scssphp/src/Parser.php</b> on line <b>2142</b><br />
```

**Comment by robocoder** [comment]
Can you try compiling with `master`?

**Comment by dtrunk90** [comment]
It happens when requesting _grid.scss. When requesting foundation.scss it works.
