### ISSUE TITLE
Error while compiling a media query in a mixin

### ISSUE THREAD

**Issue by tdutrion** [leafo/scssphp#409]
Hi,

I am definitely not expert in scss, so please be kind :)

I have some SCSS code from [HTML5up Prologue theme](http://html5up.net/prologue) that compiles well with sass installed using gem, but does not compile with scssphp.

```
vendor/bin/robo compile:scss assets/sass/main.scss assets/css/main.css -vvv


  [Leafo\ScssPhp\Exception\CompilerException]  
  Undefined variable $query: line: 1214        


Exception trace:
 () at /Users/thomas/PhpstormProjects/scotlandphp/vendor/leafo/scssphp/src/Compiler.php:3296
 Leafo\ScssPhp\Compiler->throwError() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/leafo/scssphp/src/Compiler.php:2966
 Leafo\ScssPhp\Compiler->get() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/leafo/scssphp/src/Compiler.php:1976
 Leafo\ScssPhp\Compiler->reduce() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/leafo/scssphp/src/Compiler.php:2006
 Leafo\ScssPhp\Compiler->reduce() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/leafo/scssphp/src/Compiler.php:1980
 Leafo\ScssPhp\Compiler->reduce() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/leafo/scssphp/src/Compiler.php:2494
 Leafo\ScssPhp\Compiler->compileValue() at n/a:n/a
 array_map() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/leafo/scssphp/src/Compiler.php:1243
 Leafo\ScssPhp\Compiler->compileMediaQuery() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/leafo/scssphp/src/Compiler.php:560
 Leafo\ScssPhp\Compiler->compileMedia() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/leafo/scssphp/src/Compiler.php:1444
 Leafo\ScssPhp\Compiler->compileChild() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/leafo/scssphp/src/Compiler.php:1204
 Leafo\ScssPhp\Compiler->compileChildrenNoReturn() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/leafo/scssphp/src/Compiler.php:957
 Leafo\ScssPhp\Compiler->compileBlock() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/leafo/scssphp/src/Compiler.php:1448
 Leafo\ScssPhp\Compiler->compileChild() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/leafo/scssphp/src/Compiler.php:1204
 Leafo\ScssPhp\Compiler->compileChildrenNoReturn() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/leafo/scssphp/src/Compiler.php:957
 Leafo\ScssPhp\Compiler->compileBlock() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/leafo/scssphp/src/Compiler.php:1448
 Leafo\ScssPhp\Compiler->compileChild() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/leafo/scssphp/src/Compiler.php:1204
 Leafo\ScssPhp\Compiler->compileChildrenNoReturn() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/leafo/scssphp/src/Compiler.php:957
 Leafo\ScssPhp\Compiler->compileBlock() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/leafo/scssphp/src/Compiler.php:1448
 Leafo\ScssPhp\Compiler->compileChild() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/leafo/scssphp/src/Compiler.php:1204
 Leafo\ScssPhp\Compiler->compileChildrenNoReturn() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/leafo/scssphp/src/Compiler.php:957
 Leafo\ScssPhp\Compiler->compileBlock() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/leafo/scssphp/src/Compiler.php:1448
 Leafo\ScssPhp\Compiler->compileChild() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/leafo/scssphp/src/Compiler.php:1204
 Leafo\ScssPhp\Compiler->compileChildrenNoReturn() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/leafo/scssphp/src/Compiler.php:1727
 Leafo\ScssPhp\Compiler->compileChild() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/leafo/scssphp/src/Compiler.php:1204
 Leafo\ScssPhp\Compiler->compileChildrenNoReturn() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/leafo/scssphp/src/Compiler.php:957
 Leafo\ScssPhp\Compiler->compileBlock() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/leafo/scssphp/src/Compiler.php:1448
 Leafo\ScssPhp\Compiler->compileChild() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/leafo/scssphp/src/Compiler.php:1204
 Leafo\ScssPhp\Compiler->compileChildrenNoReturn() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/leafo/scssphp/src/Compiler.php:597
 Leafo\ScssPhp\Compiler->compileMedia() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/leafo/scssphp/src/Compiler.php:1444
 Leafo\ScssPhp\Compiler->compileChild() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/leafo/scssphp/src/Compiler.php:1204
 Leafo\ScssPhp\Compiler->compileChildrenNoReturn() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/leafo/scssphp/src/Compiler.php:1710
 Leafo\ScssPhp\Compiler->compileChild() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/leafo/scssphp/src/Compiler.php:1204
 Leafo\ScssPhp\Compiler->compileChildrenNoReturn() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/leafo/scssphp/src/Compiler.php:294
 Leafo\ScssPhp\Compiler->compileRoot() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/leafo/scssphp/src/Compiler.php:193
 Leafo\ScssPhp\Compiler->compile() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/codegyre/robo/src/Task/Assets/Scss.php:62
 Robo\Task\Assets\Scss->scssphp() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/codegyre/robo/src/Task/Assets/CssPreprocessor.php:147
 Robo\Task\Assets\CssPreprocessor->compile() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/codegyre/robo/src/Task/Assets/CssPreprocessor.php:175
 Robo\Task\Assets\CssPreprocessor->run() at /Users/thomas/PhpstormProjects/scotlandphp/RoboFile.php:57
 RoboFile->compileScss() at n/a:n/a
 call_user_func_array() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/codegyre/robo/src/Application.php:32
 Robo\Application->Robo\{closure}() at n/a:n/a
 call_user_func() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/symfony/console/Command/Command.php:254
 Symfony\Component\Console\Command\Command->run() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/symfony/console/Application.php:791
 Symfony\Component\Console\Application->doRunCommand() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/symfony/console/Application.php:186
 Symfony\Component\Console\Application->doRun() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/codegyre/robo/src/Runner.php:90
 Robo\Runner->execute() at /Users/thomas/PhpstormProjects/scotlandphp/vendor/codegyre/robo/robo:19

compile:scss <src> <dest>
```

After analysing the code (by removing bits mainly), I found the problem.

``` sass
@include breakpoint(mobile) {
    #main {
        #groups {
            article:last-child {
                a {
                    @media screen and (min-height: $sm) {
                        padding-top: 15%;
                    }
                }
            }
        }
    }
}
```

Commenting out the @media block disable the error (but also the behaviour obviously...).

`$sm` is defined in the same file, above, as `$sm: 768px;`.

The breakpoint mixin is defined as follow in another file that is included:

``` sass
/// Wraps @content in a @media block using a given breakpoint.
/// @param {string} $breakpoint Breakpoint.
/// @param {map} $queries Additional queries.
@mixin breakpoint($breakpoint: null, $queries: null) {

    $query: 'screen';

    // Breakpoint.
    @if $breakpoint and map-has-key($breakpoints, $breakpoint) {
        $query: $query + ' and ' + map-get($breakpoints, $breakpoint);
    }
    // Queries.
    @if $queries {
        @each $k, $v in $queries {
            $query: $query + ' and (' + $k + ':' + $v + ')';
        }
    }
        @media #{$query} {
            @content;
        }
}
```

I am really not sure what the problem is here, but it does work with the official client (which I would be glad to avoid if possible!).

Thanks

**Comment by tdutrion** [comment]
Hi!

Back on the project and moving forward into this analysis. The problem seems to come from the string interpolation `@media #{$query}`, where `$query` is considered as not defined while it is defined and completed just above.

Any idea about what this could be?

**Comment by robocoder** [comment]
Re-testing with `master`, the error is gone, but the output is wrong, notably, double backslashes and values unexpectedly surrounded by quotes. (Interpolations gone wild?)

**Comment by Cerdic** [comment]
was hoping that #669 fixes this issue but not, even if I can guess this is about the same problem.
Just for the record a simple test case:
```
$breakpoints: (
  'mobile': 320px,
  'tablet': 768px,
  'desktop': 1024px
) !default;

$sm: 768px;

/// Wraps @content in a @media block using a given breakpoint.
/// @param {string} $breakpoint Breakpoint.
/// @param {map} $queries Additional queries.
@mixin breakpoint($breakpoint: null, $queries: null) {

    $query: 'screen';

    // Breakpoint.
    @if $breakpoint and map-has-key($breakpoints, $breakpoint) {
        $query: $query + ' and ' + map-get($breakpoints, $breakpoint);
    }
    @media #{$query} {
        @content;
    }
}

@include breakpoint(mobile) {
    #main {
        @media screen and (min-height: $sm) {
            padding-top: 15%;
        }
    }
}
```

and the result
```
Fatal error: Uncaught Leafo\ScssPhp\Exception\CompilerException: Undefined variable $query: t409.scss on line 29
Call Stack:
#0 mixin breakpoint t409.scss on line 31
 in /Users/cedric/Sites/scssphp/src/Compiler.php:3879
Stack trace:
#0 /Users/cedric/Sites/scssphp/src/Compiler.php(3505): Leafo\ScssPhp\Compiler->throwError('Undefined varia...')
#1 /Users/cedric/Sites/scssphp/src/Compiler.php(2411): Leafo\ScssPhp\Compiler->get('query')
#2 /Users/cedric/Sites/scssphp/src/Compiler.php(2441): Leafo\ScssPhp\Compiler->reduce(Array)
#3 /Users/cedric/Sites/scssphp/src/Compiler.php(2415): Leafo\ScssPhp\Compiler->reduce(Array)
#4 /Users/cedric/Sites/scssphp/src/Compiler.php(2934): Leafo\ScssPhp\Compiler->reduce(Array)
#5 /Users/cedric/Sites/scssphp/src/Compiler.php(1524): Leafo\ScssPhp\Compiler->compileValue(Array)
#6 /Users/cedric/Sites/scssphp/src/Compiler.php(3280): Leafo\ScssPhp\Compiler->evaluateMediaQuery(Array)
#7 /Users/cedric/Sites/scssphp/src/Compiler.php(3271): Leafo\ScssPhp\Compiler->multiplyMedia(Object(Leafo\ScssPhp\Com in /Users/cedric/Sites/scssphp/src/Compiler.php on line 3879
```

**Comment by Cerdic** [comment]
The test above now gives the good result:

```
  @media screen and (max-width:320px) and (min-height: 768px) {
      #main {
        padding-top: 15%; } }
```
