### ISSUE TITLE
libAbs() function makes correct Bootstrap 4.0.0 (final) build impossible

### ISSUE THREAD

**Issue by jugyhead** [leafo/scssphp#551]
The libAbs() function does return the expected value but also changes the Number object itself.

More information at twbs/bootstrap issue 2542: https://github.com/twbs/bootstrap/issues/25421

**Comment by jugyhead** [comment]
This simplified example should explain the issue:

```
$demo-color: #770000 !default;
$theme-colors: (
        "color1": $demo-color,
        "color2": $demo-color,
        "color3": $demo-color
) !default;
$alert-bg-level:        -10 !default;
$alert-text-level:      7 default;
$theme-color-interval:  8% !default;

@mixin alert-variant($background, $color) {
  color: $color;
  background-color: $background;
}

@function theme-color($key: "color1") {
  @return map-get($theme-colors, $key);
}

@function theme-color-level($color-name: "color1", $level: 0) {
  $color: theme-color($color-name);
  $color-base: if($level > 0, #000, #fff);
  $level: abs($level);

  @return mix($color-base, $color, $level * $theme-color-interval);
}

@each $color, $value in $theme-colors {
  .alert-#{$color} {
    @include alert-variant(theme-color-level($color, $alert-bg-level), theme-color-level($color, $alert-text-level));
  }
}
```

Expected result:
```
  .alert-color1 {
    color: #700;
    background-color: #e4cccc; }
  .alert-color2 {
    color: #700;
    background-color: #e4cccc; }
  .alert-color3 {
    color: #700;
    background-color: #e4cccc; }
```

Actual result:
```
  .alert-color1 {
    color: #700;
    background-color: #e4cccc; }
  .alert-color2 {
    color: #700;
    background-color: #180000; }
  .alert-color3 {
    color: #700;
    background-color: #180000; }
```

**Comment by jugyhead** [comment]
Thanks for fixing. But there is still something wrong.

```
PHP Notice:  Object of class Leafo\ScssPhp\Node\Number could not be converted to int in .../vendor/leafo/scssphp/src/Node/Number.php on line 231
PHP Fatal error:  Uncaught Error: Unsupported operand types in .../vendor/leafo/scssphp/src/Node/Number.php:231
Stack trace:
#0 .../vendor/leafo/scssphp/src/Node/Number.php(231): array_sum(Array)
#1 .../vendor/leafo/scssphp/src/Compiler.php(2092): Leafo\ScssPhp\Node\Number->unitless()
#2 .../vendor/leafo/scssphp/src/Compiler.php(3644): Leafo\ScssPhp\Compiler->reduce(Array, true)
#3 .../vendor/leafo/scssphp/src/Compiler.php(2210): Leafo\ScssPhp\Compiler->callNativeFunction('mix', Array, NULL)
#4 .../vendor/leafo/scssphp/src/Compiler.php(2187): Leafo\ScssPhp\Compiler->fncall('mix', Array)
#5 .../vendor/leafo/scssphp/src/Compiler.php(1811): Leafo\ScssPhp\Compiler->reduce(Array, true)
#6 .../vendor/leafo/scssphp/src/Compiler.php(1309): Leafo\ScssPhp\Compiler->compileChild(Array, Object(Leafo\ScssPhp\Formatter\OutputBlock))
```

**Comment by robocoder** [comment]
Ok. Will take a look again. Was that error with the simplified example? What php version?

**Comment by jugyhead** [comment]
Ah, it was my fault. Had an error in the scss:
```
$alert-bg-level:        -10 !default;
$alert-text-level:      7 !default;              // "!" was missing
$theme-color-interval:  8% !default;
```
It works perfectly now. Thanks a lot!

**Comment by robocoder** [comment]
Ok
