### ISSUE TITLE
Undefined variable $min: line: -1 (negative one)

### ISSUE THREAD

**Issue by groovenectar** [leafo/scssphp#579]
Getting this error with Google's Material Design Components for Web:

    /* Undefined variable $min: line: -1 */

With the following SCSS:
```
// Private mixins, meant for internal use.
@mixin mdc-layout-grid-media-query_($size) {
  @if not map-has-key($mdc-layout-grid-columns, $size) {
    @error "Invalid style specified! Choose one of #{map-keys($mdc-layout-grid-columns)}";
  }

  $min: mdc-layout-grid-breakpoint-min($size);
  $max: mdc-layout-grid-breakpoint-max($size);

  @if $min == null and $max != null {
    // Phone
    @media (max-width: $max) {
      @content;
    }
  } @else if $min != null and $max != null {
    // Tablet
    @media (min-width: $min) and (max-width: $max) {
      @content;
    }
  } @else if $min != null and $max == null {
    // Desktop
    @media (min-width: $min) {
      @content;
    }
  } @else {
    // Fallback - no breakpoints defined
    @content;
  }
}
```
If I remove just the `else if`s, like this:
```
// Private mixins, meant for internal use.
@mixin mdc-layout-grid-media-query_($size) {
  @if not map-has-key($mdc-layout-grid-columns, $size) {
    @error "Invalid style specified! Choose one of #{map-keys($mdc-layout-grid-columns)}";
  }

  $min: mdc-layout-grid-breakpoint-min($size);
  $max: mdc-layout-grid-breakpoint-max($size);

  @if $min == null and $max != null {
    // Phone
    @media (max-width: $max) {
      @content;
    }
  } @else {
    // Fallback - no breakpoints defined
    @content;
  }
}
```
Then there is this error, even if I increase the memory limit to almost 4GB:

    Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes)

If I remove that `if` statement entirely, the error is gone but the following `.mdc-layout-grid` declaration does not render at all (because it's using that mixin):
```
// postcss-bem-linter: define layout-grid
.mdc-layout-grid {
  @each $size in map-keys($mdc-layout-grid-columns) {
    @include mdc-layout-grid-media-query_($size) {
      $margin: map-get($mdc-layout-grid-default-margin, $size);

      @include mdc-layout-grid($size, $margin, $mdc-layout-grid-max-width);
    }
  }
}
```
Is there a way I can debug the `$min` and `$max` variables to find out what they are? Some kind of `var_dump($min, $max); exit();` possibility? Or any idea why it could have a minus sign in the line number?

**Comment by groovenectar** [comment]
Isolated the error to the following code:

```
@at-root .mdc-layout-grid__cell--span-#{$span},
  .mdc-layout-grid__cell--span-#{$span}-#{$size} {
  @include mdc-layout-grid-cell-span_($size, $span, $gutter);
}
```
Which is part of this declaration:

```
.mdc-layout-grid__cell {
  // select the upper breakpoint
  $upper-breakpoint: nth(map-keys($mdc-layout-grid-columns), 1);

  @each $size in map-keys($mdc-layout-grid-columns) {
    @include mdc-layout-grid-media-query_($size) {
      $gutter: map-get($mdc-layout-grid-default-gutter, $size);

      @include mdc-layout-grid-cell($size, $mdc-layout-grid-default-column-span, $gutter);

      @for $span from 1 through map-get($mdc-layout-grid-columns, $upper-breakpoint) {
        // Span classes.
        // stylelint-disable max-nesting-depth
        @at-root .mdc-layout-grid__cell--span-#{$span},
          .mdc-layout-grid__cell--span-#{$span}-#{$size} {
          @include mdc-layout-grid-cell-span_($size, $span, $gutter);
        }
        // stylelint-enable max-nesting-depth
      }
    }
  }

  // Order override classes.
  @for $i from 1 through map-get($mdc-layout-grid-columns, $upper-breakpoint) {
    &--order-#{$i} {
      @include mdc-layout-grid-cell-order($i);
    }
  }

  // Alignment classes.
  &--align-top {
    @include mdc-layout-grid-cell-align(top);
  }

  &--align-middle {
    @include mdc-layout-grid-cell-align(middle);
  }

  &--align-bottom {
    @include mdc-layout-grid-cell-align(bottom);
  }
}
```

**Comment by groovenectar** [comment]
Are there known issues going on with `at-root`?

I ran into the issue again, had forgotten what was going on from before...

I can see where `at-root` could be complex!

**Comment by niaccurshi** [comment]
A problem with this issue in terms of testing it is that the error I get is based on "$mdc-layout-grid-columns" not being defined. Can you also provide that variable that you're using and also the variable "$mdc-layout-grid-default-column-span"?

**Comment by groovenectar** [comment]
@niaccurshi I'm not sure of another way to provide a test case other than this:

https://drive.google.com/open?id=1D3eu-L1AgpDIFP9fZCArLmJH9X0h26uu

It contains a minimal test case in the folder `scssphp-test-case`

It has a vendor directory with scssphp, and a node_modules directory with the layout-grid component.

The test script is `test.php` and can be started with the command `php -S localhost:3000`, making it accessible at http://localhost:3000/test.php

Here is the content of `test.php`:

```
<?php

ini_set('display_errors', 1);
error_reporting(E_ALL);

require('vendor/autoload.php');

use Leafo\ScssPhp\Compiler;

$scss = new Compiler();

echo $scss->compile('@import "node_modules/@material/layout-grid/mdc-layout-grid";');
```
And here is the error:

```
Fatal error:  Uncaught Leafo\ScssPhp\Exception\CompilerException: Undefined variable $min: line: -1 in /home/dan/Development/phpscss/vendor/leafo/scssphp/src/Compiler.php:3555
--
  | Stack trace:
  | #0 /home/dan/Development/phpscss/vendor/leafo/scssphp/src/Compiler.php(3199): Leafo\ScssPhp\Compiler-&gt;throwError('Undefined varia...')
  | #1 /home/dan/Development/phpscss/vendor/leafo/scssphp/src/Compiler.php(2166): Leafo\ScssPhp\Compiler-&gt;get('min')
  | #2 /home/dan/Development/phpscss/vendor/leafo/scssphp/src/Compiler.php(2684): Leafo\ScssPhp\Compiler-&gt;reduce(Array)
  | #3 /home/dan/Development/phpscss/vendor/leafo/scssphp/src/Compiler.php(1383): Leafo\ScssPhp\Compiler-&gt;compileValue(Array)
  | #4 /home/dan/Development/phpscss/vendor/leafo/scssphp/src/Compiler.php(685): Leafo\ScssPhp\Compiler-&gt;compileMediaQuery(Array)
  | #5 /home/dan/Development/phpscss/vendor/leafo/scssphp/src/Compiler.php(1606): Leafo\ScssPhp\Compiler-&gt;compileMedia(Object(Leafo\ScssPhp\Block))
  | #6 /home/dan/Development/phpscss/vendor/leafo/scssphp/src/Compiler.php(1335): Leafo\ScssPhp\C in <b>/home/dan/Development/phpscss/vendor/leafo/scssphp/src/Compiler.php</b> on line <b>3555</b>
```

Some details I have about the `$min` variable are outlined here: https://github.com/leafo/scssphp/issues/579#issue-333987473

I hope this helps

**Comment by groovenectar** [comment]
@niaccurshi Do you know of a service like CodePen but for PHP, where I can add some files to a sandbox for linking?

**Comment by Cerdic** [comment]
there is good chance that #647 fixes this issue as it includes a big fix on at-root

**Comment by Cerdic** [comment]
this issue can definitely be closed @robocoder 
I can compile without any trouble the file `node_modules/@material/layout-grid/mdc-layout-grid.scss` given in the zip archive

**Comment by groovenectar** [comment]
Awesome news! Sounds solid. Great work on `at-root` @Cerdic
