### ISSUE TITLE
ParserException

### ISSUE THREAD

**Issue by lewisdonovan** [leafo/scssphp#603]
Hi,
I'm getting the following error when I run the compiler:

```
Leafo\ScssPhp\Exception\ParserException: parse error: failed at `0` (stdin) on line 1 in /path/to/scssphp/src/Parser.php:128
Stack trace:
#0 /path/to/scssphp/src/Parser.php(169): Leafo\ScssPhp\Parser->throwParseError()
#1 /path/to/scssphp/src/Compiler.php(197): Leafo\ScssPhp\Parser->parse(0)
#2 /path/to/my-custom-code.php(15): Leafo\ScssPhp\Compiler->compile(0)
```

The code is `my-custom-code.php` is:

```
<?php 
require_once 'path/to/scssphp/scss.inc.php';
use Leafo\ScssPhp\Compiler;

    $scss = new Compiler();
    $styles_sass = file_get_contents('path/to/sass/main.sass');

    $vars = array(
        'bg' => '#000',
        'primary' => '#fff'
    );
    $scss->setVariables($vars);

    try {
        echo $scss->compile( $styles_sass );
    } catch(Exception $e) {
        echo 'error';
        echo PHP_EOL . $e;
    }

?>
```

Not sure if it makes a difference, but I'm using indented Sass syntax, and am also importing Sass files into my `main.sass` file. Thanks

**Comment by robocoder** [comment]
ScssPhp doesn't support indented Sass syntax.

**Comment by lewisdonovan** [comment]
Great, cheers
